language: python
env:
- TOXENV=py27
- TOXENV=py34
install:
- pip install tox
script:
- tox
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
deploy:
  provider: pypi
  user: billy.shambrook
  password:
    secure: PDnaQH8W0v6cPSPSktcuZ/H5iMkWbyMTtL5FhWoLcv/vq+daWbQniKivjB1kkUXNpTLsfsZSiDNEuIYRFMmeiA8EzrBuiVqSg9p77R/WrZv3pzkkzEkMuLR4ENPUbI57QNpC2yo3hgfMP/BFS8CxLpr5w0MNOOpaP5eGHnyIE488IS5UzocY3uUGCZXXTjwvi1MyFxYD7GFZn/bs70mg4CbJFYOr7I07BDCd47eamAqZNrxUU7JkAh8TiWZwBS3XrflqAg7ESc7xa/Ogsf6d2R6tbsubrZOMYkIETNLeptPGGzlQBb8EOv/vH1XkVhu9c9YOtJELQSNvVEtwnANyRLAOkKVB1ouCue9Y1uQdQ4SGV8cSwqOzspEZDEhirauX3zmM3xYHqRwdBNHJ9hJMYjEAC8Sffn4Vbb/xY8m3PC5553BcXENm2oAxsuOest0R6FJ7VqQsAnpqmkW0BbuobRD5lo3Beuw8frIWfq8CqoI9iKIS2VGE8B0jdeHvolmc+MT3/t66vKuGzWviUeEEVgia2rD+qAOczejFVOz4N1RgOl1Ugg4lvZMUDDMfeWPpruabtfX8frkjNLoRTSD3Cq9wmxunizRfirHjnRda+hs8XN0C/oYijMcmCCiQD6xLfj2C16DfWqvy4HvU0318t+r0JSW6Gol0Rrzc44Qe5J4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: billyshambrook/taskman
