language: python
env:
- TOXENV=py27
- TOXENV=py34
install:
- pip install tox
script:
- tox
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
deploy:
  provider: pypi
  user: billy.shambrook
  password:
    secure: FpgBTiwisTDic6jPGKcqkqokDhmEAz//1Zse0RQEHhyKslpOuk+VqsloIPvyTlkkvisbVhIdiizjudFa/1YEW4yX19/z35+3Q9VATvR2uWowygFsO1rEinlqVeTThk6effJOVlamJZMDAPPhtK+StHkoujZ5hDsq6hvFx4supANUBU+4cuKuJKggcz3wT8OFYK3iycR/5G2S2L9nscS05kZjYByz2Fj3KCg81XXhmGRb1O3tleLEugEq08WWv3q+maV7VoYGmOnQpqKPn6G0iNWbOP7Nd4MQ0w07vUWJiRIELg1MtwTtkppSILzCiaMQOhJ+SSACczQFWjUoCIyPU6vpp1jnO8udbMn8tL4KCbMhNmwnB+F98QtsuSbOW6+9sz2p85Vh3rSHmuTulcTNKra2DwdvtD/csdL9c0qbkDYx3AympTzDcQ7pxswsV7riSagDiJeq4dJRyd5rWizS2nLR8i/Q6zHi5tEEoEy13g2MUzvBI43DWkMrCsuaKMJJMS9tyECU1TQI2EwFNHOJuhxmBcRQaZ+db2buuBJmBNNvp6yRnvAklsJQFeLi/wX//T4bgwG3NrVIsVnlVFeTMpQpPUSL/3CNMA1NehGt54R1OXYqG9+UtgF7RKptZTbw7MAkN61OM+8geHF5+6ovwWCpFG3MzlG1w5fIlEHyXRY=
  on:
    tags: true
    repo: billyshambrook/taskman
