language: python
env:
    - TOXENV=py27
    - TOXENV=py34
install:
    - pip install tox
script:
    - tox
# Python 3.5 has to go here until Travis adds it to the default build images.
# https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
